### ISSUE TITLE
Can't edit server method

### ISSUE THREAD

**Issue by bidolah** [arasplm/ArasVSMethodPlugin#76]
### Installed product versions
- Visual Studio 2017 Professional
- This extension: 1.4.148

### Description
Replace this text with a short description

### Steps to recreate
1. Open Visual Studio and create Aras Innovator 12 Method Template project
2. Connect to the server using admin user
3. Click "Open method from Aras Innovator" and select server method 

### Current behavior
 
![image](https://user-images.githubusercontent.com/9832538/67669905-7a520500-f97b-11e9-992f-e86fb7d3e6c0.png)

Code from method loaded but "Save"/"Update" command doesn't work

### Expected behavior
Method should be opened without errors

**Comment by VladymyrAfanasiev** [comment]
Fixed by next commit:
Revision: 1110f49e89cae5dcb61cd13e99502770de1faec9
Author: Volodymyr Afanasiev
Date: 11/6/2019 11:29:24 AM
Message:
76 Can't edit server method. Added try-catch in case when "Edit.Goto" is broken in VS.

For some configuration of VS "Edit.Goto"
not works from code.
----
Modified: Aras.VS.MethodPlugin/SolutionManagement/ProjectManager.cs

**Comment by VladymyrAfanasiev** [comment]
@bidolah please verify the fix.

**Comment by bidolah** [comment]
@VladymyrAfanasiev thanks, all work fine!
